//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Praktika_Business.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainTable
    {
        public int ID { get; set; }
        public int IDClient { get; set; }
        public int IDOrder { get; set; }
        public int IDResources { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Order Order { get; set; }
        public virtual Resources Resources { get; set; }
    }
}
